# Generated by Django 5.0.1 on 2024-02-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('party_enum_type_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hotwax.party')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('marital_status_enum_id', models.CharField(blank=True, max_length=20, null=True)),
                ('employment_status_enum_id', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('placed_date', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('status_id', models.CharField(blank=True, max_length=20, null=True)),
                ('currency_uom_id', models.CharField(blank=True, max_length=20, null=True)),
                ('product_store_id', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_channel_enum_id', models.CharField(blank=True, max_length=20, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotwax.party')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('charge_shipping', models.CharField(blank=True, max_length=1, null=True)),
                ('returnable', models.CharField(blank=True, max_length=1, null=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotwax.party')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('order_item_seq_id', models.CharField(max_length=20)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('unit_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('item_type_enum_id', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotwax.product')),
            ],
        ),
    ]
