# Generated by Django 5.0.1 on 2024-02-03 07:43

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotwax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='credit_card',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
